### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by trygve** [ravndal/hacs_flexit_bacnet#2]
Just tried this HACS integration as I have a brand new Flexit Nordic unit.
However, I get an error when trying to add the integration (after downloading it using HACS, and restarting HA).

Error
Config flow could not be loaded: {"message":"Invalid handler specified"}

From the log there is this:
2023-07-31 22:17:19.311 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration flexit_no_cloud: No module named 'flexit_no_cloud'

**Comment by trygve** [comment]
So I poked around a little and got a bit further.
I changed the DOMAIN value in const.py to "flexit_no_cloud" 
And in config_flow.py I change the following import:
from flexit_no_cloud import FlexitBACnet -> from flexit_bacnet import FlexitBACnet*

That resolved the previous issue and I now see the config window pop up asking me for ip and device number.
When I give the correct values a new error appears:
```
Logger: aiohttp.server
Source: setup.py:230
First occurred: 19:39:49 (1 occurrences)
Last logged: 19:39:49

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 181, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 296, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 420, in _async_handle_step
    result = await self.async_finish_flow(flow, result.copy())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 952, in async_finish_flow
    await self.config_entries.async_add(entry)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1069, in async_add
    await self.async_setup(entry.entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1211, in async_setup
    result = await async_setup_component(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/setup.py", line 102, in async_setup_component
    return await task
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/setup.py", line 230, in _async_setup_component
    domain in processed_config
TypeError: argument of type 'function' is not iterable
```

Any idea what is going on here @ravndal ? Does this integration work for you or is it still in development?

**Comment by ravndal** [comment]
Still in development. For now, I would just go with the cloud-connected one. It's slower to update but has been really stable.
